language: go
go: 
  - "1.14"
before_install:
  - openssl aes-256-cbc -K $encrypted_492c890bafbd_key -iv $encrypted_492c890bafbd_iv -in deploy.enc -out ./deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 0600 ./deploy
  - ssh-add ./deploy
install:
- pyenv global 3.7
- pip3 install ansible
- "./configure"
- make
- echo '$secret_sc' > ansible/secret.txt
script:
- make test
deploy:
  skip_cleanup: true
  - provider: script
    script: cd ansible && ansible-playbook -i hosts eveleve.yaml
    on:
      branch: master
